### PR TITLE
Add problem matcher to annotate flake8 errors in PRs.

### LINKED ISSUE #174: Reviewdog doesn't appear to work on forks
Output from a CI:
```
[action-flake8] Checking python code with the flake8 linter and reviewdog...
reviewdog: This GitHub token doesn't have write permission of Review API [1], 
reviewdog: Reporting results for "flake8"
```

A solution is to convert over a manual annotation script.

### PR DESCRIPTION
**Pull request by ehpor**
Fixes #174 by removing reviewdog as a dependency.

### CODE REVIEW

**Comment by ivalaginja** [comment]
Is this supposed to already fix things for the tests on this branch? Asking because they're still waiting for the flake8 status to be reported after all tests finished and passed.

**Comment by ehpor** [comment]
> Is this supposed to already fix things for the tests on this branch? Asking because they're still waiting for the flake8 status to be reported after all tests finished and passed.

I think that `flake8` requirements is for reviewdog, which is being disabled by this PR. If so, I should make it optional. I'll look into that now.

FYI, this is a copy of the `hicat-package2` problem matcher.

**Comment by ehpor** [comment]
Unconfirmed, since Github doesn't tell me the source other than "Github Action", but likely that came from reviewdog. I removed it anyway, since the Lint action takes care of that now.

**Review by ivalaginja — APPROVED** [review]
Ok - looks good to me in that case.

**Pull request merged**
